### ISSUE TITLE
"Repository" is a less good conceptual entrypoint

### ISSUE THREAD

**Issue by davidmiller** [pacharanero/proposed-apperta-repo-management#2]
(Or alternatively, I don't understand what you're doing.)

Apperta would be better having a policy about "Working in the open" with a section on source code management.

**Comment by pacharanero** [comment]
This proposal emerged directly from a discussion about what to do with various repositories so, in an effort not to start by boiling the ocean, I focused purely on repository management. Other documents may follow.

> Apperta would be better having a policy about "Working in the open" with a section on source code management.

Agreed. I'd like for that to happen, and for that policy to be created and managed in the same way, in an open repository. And I hope that this proposal document eventually forms part of the source code management section.

**Comment by davidmiller** [comment]
Fixed by #3 closing!
